-- EduMap Consolidated Crawled Data
-- Generated: 2026-06-06 13:20:52
-- This includes: WiFi, Green Spaces, Books, Libraries, Schools
-- Target: PostgreSQL with PostGIS extension

-- ============================================
-- WiFi Hotspots
-- ============================================
INSERT INTO map_points (id, name, description, location) VALUES ('b7870da8-0762-471f-a8cd-a43db1eea861', 'Công viên Biên Hùng', 'wifi_park', ST_SetSRID(ST_MakePoint(106.8245, 10.9155), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('7871bc84-874f-4e8c-b527-dc8bc9b78202', 'Công viên Dương Tử Giang', 'wifi_park', ST_SetSRID(ST_MakePoint(106.835, 10.9485), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('274f03a1-0a17-44a5-87d7-da388807d822', 'Trạm xe buýt Trung tâm Biên Hòa', 'wifi_transport', ST_SetSRID(ST_MakePoint(106.8246, 10.9246), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('a0ce11e4-3580-416e-b383-6960229d8b09', 'Thư viện Đông Nái', 'wifi_library', ST_SetSRID(ST_MakePoint(106.8195, 10.9258), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('5999d781-4f2e-4feb-8dba-2c2a4154ceab', 'Nhà Văn Hóa Khu phố 1', 'wifi_community', ST_SetSRID(ST_MakePoint(106.865, 10.9673), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('d53c225f-035f-4b11-8a16-d78fed2f0fba', 'Trường Đại học Công nghệ Đông Nái (DNTU)', 'wifi_education', ST_SetSRID(ST_MakePoint(106.8686, 10.9835), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('a1df6300-db8a-4749-b925-519a064750d2', 'Quán cà phê Wifi Zone - 30 Tháng 4', 'wifi_cafe', ST_SetSRID(ST_MakePoint(106.829, 10.928), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('b5dbe496-b800-44a9-87b1-1df14cf80640', 'Trung tâm Thương mại Hoàng Phúc', 'wifi_mall', ST_SetSRID(ST_MakePoint(106.84, 10.93), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('4fa7cb50-36c3-40ae-96c6-315e79f3ba22', 'Bệnh viện Đa khoa Biên Hòa', 'wifi_health', ST_SetSRID(ST_MakePoint(106.828, 10.945), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('13607c78-2ebd-4970-b138-a46dabb0b558', 'Khu công nghiệp Amata', 'wifi_industrial', ST_SetSRID(ST_MakePoint(106.915, 10.895), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('e9d8063b-3938-4958-99a4-e19627217b26', 'Long Bình Plaza', 'wifi_residential', ST_SetSRID(ST_MakePoint(106.925, 10.915), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('082f6ee8-0bcb-4e14-858e-a685496cd4e2', 'Thư viện Tỉnh Đông Nái - Thành phố Thủ Dầu Một', 'wifi_provincial_library', ST_SetSRID(ST_MakePoint(106.7345, 10.885), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('ddd6fe6e-7570-4383-bf62-04478a99ddfb', 'Trường Đại học Nông Lâm TPHCM - Chi nhánh Đông Nái', 'wifi_education', ST_SetSRID(ST_MakePoint(106.75, 10.92), 4326)::geography);

-- ============================================
-- Green Spaces
-- ============================================
INSERT INTO map_points (id, name, description, location) VALUES ('a1f98ab5-2ac7-4cad-8dde-1a6e782b89c5', 'Công viên Biên Hùng', 'park', ST_SetSRID(ST_MakePoint(106.8245, 10.9155), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('4fe245f1-9fdb-4c4b-94c2-62a11983ff9e', 'Công viên Dương Tử Giang', 'park', ST_SetSRID(ST_MakePoint(106.835, 10.9485), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('bba67337-37d6-40a4-bff7-3bb336f6e99a', 'Hồ Trữ Nước Tươi - Khu Công viên Sinh thái', 'ecological_park', ST_SetSRID(ST_MakePoint(106.85, 10.92), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('9eefdbb5-a1e9-41e2-b932-946f970fdd33', 'Khu Vườn Cây Xanh Nguyễn Khuyến', 'botanical_garden', ST_SetSRID(ST_MakePoint(106.87, 10.98), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('bca54d7c-b5a4-4218-8f6f-75d7fa936f06', 'Công viên Tây Thạnh', 'wellness_park', ST_SetSRID(ST_MakePoint(106.86, 10.935), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('d6e10998-38f6-478e-84c1-1317220e3c18', 'Vườn Nho Biên Hòa', 'agro_tourism', ST_SetSRID(ST_MakePoint(106.93, 10.885), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('c9eea764-a547-4b45-b91f-bf0d3cbcfdd2', 'Công viên Quốc gia Tây Ninh (gần biên giới Đông Nái)', 'national_park', ST_SetSRID(ST_MakePoint(106.7, 10.82), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('233633dd-3f61-4e83-b59e-b90f14ad2c29', 'Ven sông Sài Gòn - Khu dạo bộ sinh thái', 'riverside_park', ST_SetSRID(ST_MakePoint(106.82, 10.91), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('9f3c08be-777c-411b-bbc0-1ced9b120d9b', 'Dự án Sống Xanh - DNTU', 'green_initiative', ST_SetSRID(ST_MakePoint(106.8686, 10.9835), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('8f35ab93-ffc8-400d-96e9-cc34f8d13f1d', 'Hội Bảo Vệ Môi Trường Biên Hòa', 'environmental_org', ST_SetSRID(ST_MakePoint(106.83, 10.93), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('f44c7fc2-8564-436a-8602-0afb300406a7', 'Chương trình Rác thải Zero - Biên Hòa', 'sustainability_program', ST_SetSRID(ST_MakePoint(0, 0), 4326)::geography);

-- ============================================
-- Libraries
-- ============================================
INSERT INTO map_points (id, name, description, location) VALUES ('137796ae-0569-49ac-91d7-dfdbad77f137', 'Thư viện Tỉnh Đông Nái', 'library', ST_SetSRID(ST_MakePoint(106.7345, 10.885), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('29beb70c-16a1-4dff-9b44-cf4896620c4d', 'Thư viện Đại học Công nghệ Đông Nái (DNTU)', 'library', ST_SetSRID(ST_MakePoint(106.8686, 10.9835), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('d2c965a8-ec11-4c94-8349-8d7ac94e6abf', 'Thư viện Quận Biên Hòa', 'library', ST_SetSRID(ST_MakePoint(106.83, 10.93), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('ed249cc1-2110-44ea-b43b-e3e33301132d', 'Thư viện Trường Cao đẳng Kỹ thuật Đông Nái', 'library', ST_SetSRID(ST_MakePoint(106.82, 10.92), 4326)::geography);

-- ============================================
-- Schools & Educational Institutions
-- ============================================
INSERT INTO map_points (id, name, description, location) VALUES ('88695d89-4e94-43f1-8b98-870d86577b7f', 'Trường Đại học Công nghệ Đông Nái (DNTU)', 'school', ST_SetSRID(ST_MakePoint(106.8686, 10.9835), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('ecfc0faa-8933-401c-8ca5-07adea16fd7a', 'Trường Đại học Nông Lâm TPHCM - Chi nhánh Đông Nái', 'school', ST_SetSRID(ST_MakePoint(106.75, 10.92), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('52504f1b-b466-4a1d-bf04-79edff0e7974', 'Trường Tiểu học Lý Thường Kiệt (Cơ sở 2)', 'school', ST_SetSRID(ST_MakePoint(106.8724, 10.9669), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('bd449294-fe3e-4bc3-974a-d2957fc2b3c3', 'Trường THPT Thanh Đa', 'school', ST_SetSRID(ST_MakePoint(106.83, 10.94), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('3325d9e6-d344-4d7e-b5c3-fc27b8eb62ef', 'Trường THPT Hiệp Hòa', 'school', ST_SetSRID(ST_MakePoint(106.845, 10.955), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('d877177c-89f4-4c89-963d-31dd7b01d92c', 'Trường THPT Biên Hòa', 'school', ST_SetSRID(ST_MakePoint(106.825, 10.93), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('ee58ed9b-ccf2-46a6-bff3-c6aef3b09b68', 'Trường THCS Ngô Quyền', 'school', ST_SetSRID(ST_MakePoint(106.835, 10.935), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('70d6c89e-808a-4306-a1cc-f4ecccd60575', 'Trung tâm Đào tạo Kỹ năng - DNTU', 'education', ST_SetSRID(ST_MakePoint(106.87, 10.984), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('0c7119e8-959d-4a0b-8daf-8fe0b4c3adbb', 'Khu Công nghiệp Amata - Tech Hub', 'innovation_space', ST_SetSRID(ST_MakePoint(106.915, 10.895), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('9e1a0e20-be3c-4e7d-870b-5eb6388ef422', 'Long Bình Startup Hub', 'innovation_space', ST_SetSRID(ST_MakePoint(106.925, 10.915), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('c405daca-5d2b-4f8e-ab7d-3c2b88414313', 'Trung tâm Khởi nghiệp Đông Nái', 'innovation_space', ST_SetSRID(ST_MakePoint(106.83, 10.93), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('e94bcaea-0ef3-44b4-a6c2-7e5c09ddab13', 'DNTU - Phòng Lab STEM', 'education', ST_SetSRID(ST_MakePoint(106.8687, 10.9836), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('5cc438b3-2bfc-48d0-b348-931d04cb5f69', 'DNTU - Thư viện Trung tâm', 'education', ST_SetSRID(ST_MakePoint(106.8686, 10.9835), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('0b62cd95-c819-4ee1-a730-6634b4da1c18', 'DNTU - Sống Xanh Initiative', 'sustainability', ST_SetSRID(ST_MakePoint(106.8686, 10.9835), 4326)::geography);
INSERT INTO map_points (id, name, description, location) VALUES ('2cc7ecd4-a0f7-4414-a757-0966b11efd65', 'DNTU - Incubator & Business Center', 'innovation_space', ST_SetSRID(ST_MakePoint(106.8686, 10.9835), 4326)::geography);

-- ============================================
-- Learning Materials (Books)
-- ============================================
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('05797004-2fd4-4ac6-8ba0-d19df38b43fe', 'Clean Code', 'Author: Robert C. Martin', 'Information Technology', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('90429578-d8b3-4dd4-8874-7bb89850a3f1', 'The Pragmatic Programmer', 'Author: David Thomas, Andrew Hunt', 'Information Technology', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('a7bf2d5a-1292-42a7-81e5-37f34a4b15fb', 'Design Patterns', 'Author: Gang of Four', 'Information Technology', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('714fe0de-18c0-46b3-babe-804667569cdf', 'Refactoring', 'Author: Martin Fowler', 'Information Technology', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('7654f06a-b240-48a4-a516-415cd0cb8555', 'The Mythical Man-Month', 'Author: Frederick P. Brooks Jr.', 'Information Technology', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('a94e5402-6be1-48fa-be37-bdb63ca0fc13', 'Introduction to Algorithms', 'Author: Cormen, Leiserson, Rivest', 'Information Technology', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('3052ed50-5833-45a3-adac-13bb93447a7e', 'Code Complete', 'Author: Steve McConnell', 'Information Technology', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('4e176994-e70a-4d4d-8e49-94c63c2c248e', 'Structure and Interpretation of Computer Programs', 'Author: Abelson, Sussman', 'Information Technology', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('80ba8f6f-0c61-4b88-8af9-79724f715ef0', 'The C Programming Language', 'Author: Kernighan, Ritchie', 'Information Technology', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('e1536e40-7ea1-49b1-8ca1-c690168dbefd', 'Programming Pearls', 'Author: Jon Bentley', 'Information Technology', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('d64e53e1-794c-49f8-8e3d-ea7bddf6933e', 'Effective C++', 'Author: Scott Meyers', 'Information Technology', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('ab53b5f9-032c-4659-8ea7-411a5893a893', 'The Art of Computer Programming', 'Author: Donald Knuth', 'Information Technology', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('c5095b77-5e15-4b1a-a257-1f018fd98c26', 'Database System Concepts', 'Author: Silberschatz, Korth, Sudarshan', 'Information Technology', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('532c85f8-11f7-4c6a-9f66-1682f59170db', 'Operating System Concepts', 'Author: Silberschatz, Galvin, Gagne', 'Information Technology', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('599dbfb8-776c-4c4a-a1a1-f35909b999b0', 'Computer Networks', 'Author: Andrew Tanenbaum', 'Information Technology', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('94b255c2-d152-438c-bbfe-b97008772b71', 'Web Security Testing Cookbook', 'Author: Stuttard, Pinto', 'Information Technology', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('399fb581-e87f-4e5e-b1ad-6ddd59ab34ca', 'Artificial Intelligence', 'Author: Stuart Russell, Peter Norvig', 'Information Technology', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('128a670e-42dd-4631-b9c0-2ac23762e5d3', 'Machine Learning', 'Author: Tom Mitchell', 'Information Technology', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('91d2638b-092a-4d62-aa19-fa23839539fa', 'Deep Learning', 'Author: Goodfellow, Bengio, Courville', 'Information Technology', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('49125c36-81d1-4990-a8e1-78425ea88bbb', 'Natural Language Processing with Python', 'Author: Bird, Klein, Loper', 'Information Technology', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('b89169dc-fc89-42c4-a394-c451ecbee10f', 'Concrete Mathematics', 'Author: Graham, Knuth, Patashnik', 'Computer Science', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('a0289c77-8a8a-42a1-b515-c1ab5f772a63', 'Discrete Mathematics and Its Applications', 'Author: Kenneth H. Rosen', 'Computer Science', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('2659a86d-4373-43d5-8f25-8824f5e0e809', 'Theory of Computation', 'Author: Michael Sipser', 'Computer Science', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('c14be1eb-631d-45b2-851c-88aafd29a2d9', 'Algorithms', 'Author: Robert Sedgewick', 'Computer Science', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('896d1199-75ed-4602-b6f2-9ba1ce2a061b', 'Algorithm Design Manual', 'Author: Steven Skiena', 'Computer Science', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('9c1be0f1-71ef-49ad-b44f-45adf6b0260c', 'Compilers', 'Author: Aho, Lam, Sethi, Ullman', 'Computer Science', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('4eb1b440-1a18-4c68-8dfa-934cf7826d95', 'Artificial Intelligence Modern Approach', 'Author: Russell, Norvig', 'Computer Science', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('4c64ed80-6dc0-4337-aa39-cdef70e30a9e', 'Human-Computer Interaction', 'Author: Steve Krug', 'Computer Science', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('19fb3f7f-dca9-4a4d-a01f-7390def1918b', 'Software Architecture Design', 'Author: Neal Ford', 'Computer Science', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('cc68242c-d660-4a8b-9518-1c38e1699220', 'Test Driven Development', 'Author: Kent Beck', 'Computer Science', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('6fa3c3ab-f951-4a3c-aabf-caa102475be8', 'Continuous Integration', 'Author: Paul M. Duvall', 'Computer Science', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('ef97f21c-2cee-473d-8eba-f81563b9301c', 'Release It', 'Author: Michael Nygard', 'Computer Science', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('5bb2aa5a-6c44-4e14-8453-0518b97ac1df', 'The Phoenix Project', 'Author: Gene Kim, Kevin Behr, George Spafford', 'Computer Science', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('d7d204e9-cfbe-4423-8eb2-8161df4182c4', 'Microservices Architecture', 'Author: Sam Newman', 'Computer Science', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('44e263c8-e588-4b75-8c3f-3c9bd7c35347', 'Site Reliability Engineering', 'Author: Beyer et al.', 'Computer Science', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('7033db83-01cc-471b-8407-fabe0e0a86b3', 'DevOps Handbook', 'Author: Gene Kim et al.', 'Computer Science', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('22635771-0406-4750-87a5-c67e0e6b1c36', 'Infrastructure as Code', 'Author: Kief Morris', 'Computer Science', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('29f1fb12-0ef7-4694-9dab-05e4b97759b7', 'The Google SRE Book', 'Author: Google', 'Computer Science', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('1439894c-c61f-4c54-974a-510c503a276f', 'Kubernetes in Action', 'Author: Marko Luksa', 'Computer Science', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('1801d093-f558-49db-a2fb-fd4f418efe7f', 'Docker in Action', 'Author: Jeff Nickoloff', 'Computer Science', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('888b0031-3da0-4a28-8c55-fd9869453823', 'Digital Transformation', 'Author: Thierry Breton', 'Digital Transformation', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('6553c1a2-60ce-48c5-ae60-14e9d33b3b2e', 'The Digital Divide', 'Author: Mark Warschauer', 'Digital Transformation', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('18e40e14-2342-4f29-a2a8-340264a1b922', 'Future Perfect', 'Author: Steven Johnson', 'Digital Transformation', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('8239c609-bc5f-46f2-9b27-67a8420e2d32', 'The Innovators', 'Author: Walter Isaacson', 'Digital Transformation', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('bfad2d22-359b-4386-a21e-0f675c19addb', 'Code Name', 'Author: Jennifer Doudna, Siddhartha Mukherjee', 'Digital Transformation', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('40cfb3c3-0c4f-4340-9d6c-1163695c79af', 'The Alignment Problem', 'Author: Brian Christian', 'Digital Transformation', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('e624a296-820c-4f4d-b47e-e7e1dfa9f8a6', 'Competing Against Luck', 'Author: Clayton Christensen', 'Digital Transformation', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('5af49454-772f-403c-a43f-6b517bcd519c', 'The Lean Startup', 'Author: Eric Ries', 'Digital Transformation', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('e0b97229-46c7-4dcf-89e4-3924c5bb2d53', 'Zero to One', 'Author: Peter Thiel', 'Digital Transformation', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('34892625-107c-440f-9f0c-f7c5e7ce3e84', 'The Platform Revolution', 'Author: Choudary, Parker, Van Alstyne', 'Digital Transformation', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('b286a14a-ff19-4f3d-943c-8ce971017035', 'Machine Learning Yearning', 'Author: Andrew Ng', 'Digital Transformation', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('7c972fd9-ee6c-4c50-ac8c-8c7ce6db4566', 'AI Superpowers', 'Author: Kai-Fu Lee', 'Digital Transformation', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('f17eb7c5-51b8-474b-a12f-71f7cef08915', 'The Fourth Industrial Revolution', 'Author: Klaus Schwab', 'Digital Transformation', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('4e197724-9494-4db3-bdd9-f35567fbec71', 'Abundance', 'Author: Peter Diamandis, Steven Kotler', 'Digital Transformation', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('286ce52f-640b-41b0-a7c9-8ed4be3754a2', 'Exponential Organizations', 'Author: Salim Ismail et al.', 'Digital Transformation', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('e0c6227a-e36e-4b4e-8486-761e4845681f', 'Bold', 'Author: Peter Diamandis, Steven Kotler', 'Digital Transformation', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('41298537-19f1-40d1-82b2-35c22ffb5f11', 'The Technology Trap', 'Author: Carl Benedikt Frey', 'Digital Transformation', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('c82b3bb5-97f7-4f41-998d-7d55f4e0d44f', 'Dataclysm', 'Author: Christian Rudder', 'Digital Transformation', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('5bd28a60-e404-427e-b41f-f1af770919be', 'Weapons of Math Destruction', 'Author: Cathy O''''Neil', 'Digital Transformation', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('4365eb00-0a6d-452a-a2ff-6433a91da0a4', 'Sapiens', 'Author: Yuval Noah Harari', 'Digital Transformation', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('8c5a6ef9-f463-4ef2-8fbd-f9908b966784', 'Mindset', 'Author: Carol S. Dweck', 'Education', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('a7989667-0dad-484b-8459-1216f30410c2', 'Learning How to Learn', 'Author: Barbara Oakley', 'Education', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('0ed2014b-4032-42e0-b8a2-7388af73b515', 'Make It Stick', 'Author: Brown, Roediger, McDaniel', 'Education', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('e74ae937-45c3-453e-9dfe-8ae2f84a5356', 'Teach Like a Champion', 'Author: Doug Lemov', 'Education', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('42deb614-2f40-41e1-a9ed-feb7efecc290', 'The Teaching Gap', 'Author: James Stigler, James Hiebert', 'Education', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('d3090a7e-3f39-4d0e-af60-15d64c9f86fa', 'Pedagogy of the Oppressed', 'Author: Paulo Freire', 'Education', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('b09d72b0-778c-4972-8c85-131feb666633', 'The Art of Teaching', 'Author: Gilbert Highet', 'Education', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('f7f3e42c-10d3-4d7d-8579-a9083e152749', 'Culturally Responsive Teaching', 'Author: Geneva Gay', 'Education', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('6f401644-05fc-4aab-9d74-085dd82169ae', 'Emotional Intelligence in Education', 'Author: Daniel Goleman', 'Education', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('ca54978a-dbb2-48df-b570-b794cfe8bfc9', 'Excellent Sheep', 'Author: William Deresiewicz', 'Education', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('92b97c74-1e78-4d56-b14f-5f152ff5730d', 'The End of the Myth of Learning Styles', 'Author: Paul Kirschner', 'Education', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('893fff87-39ff-43b0-9ef8-c9a0b5d5cc56', 'Classroom Management', 'Author: H. Jerome Freiberg', 'Education', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('e514b946-c771-4440-9317-5218840c62c2', 'Student-Centered Learning in Higher Education', 'Author: K. Lea', 'Education', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('943f50f5-07b8-48a3-91fb-2cac6af53ed4', 'Design for All Learners', 'Author: David Rose', 'Education', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('f121fccf-1e79-4be5-a3f7-b02ce01a8836', 'Teaching Naked', 'Author: Jose Bowen', 'Education', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('f65cbcde-0fee-4027-9585-69e47720c142', 'The Courage to Teach', 'Author: Parker Palmer', 'Education', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('a238bcb8-891b-4b84-aa97-6a07f7314e3c', 'Visible Learning', 'Author: John Hattie', 'Education', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('3ad96573-0a93-4006-9347-37623819c71f', 'Deep Learning', 'Author: Marcia Conner', 'Education', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('23d1c812-6c9b-4f6c-a966-9efc405b540b', 'The Flipped Classroom', 'Author: Jonathan Bergmann', 'Education', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
INSERT INTO learning_materials (id, title, description, subject, thumbnail_url, type, status) VALUES ('05067816-2b5a-4dea-8ca3-38efd9cbbe78', 'Mobile Learning', 'Author: Ally M.', 'Education', 'https://covers.openlibrary.org/b/id/placeholder-M.jpg', 'book', 'published');
