import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialProductionSchema1779564533609 implements MigrationInterface {
    name = 'InitialProductionSchema1779564533609'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "roles" ("id" character varying(50) NOT NULL, "name" character varying(255) NOT NULL, "description" text, CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "opportunities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "category" character varying NOT NULL, "description" text, "location_point" geography(Point,4326), "address" character varying, "deadline" TIMESTAMP WITH TIME ZONE, "is_team_finding_open" boolean NOT NULL DEFAULT false, "tags" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_4bd9cd12ddc0ff48a5a97ddebce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e3e22934a7a2b943002a81c48f" ON "opportunities" USING GiST ("location_point") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password_hash" character varying NOT NULL, "role_id" integer NOT NULL DEFAULT '11', "full_name" character varying, "avatar_url" character varying, "phone" character varying, "bio" text, "mbti_type" character varying, "skills" text array NOT NULL DEFAULT '{}', "interests" text array NOT NULL DEFAULT '{}', "points" integer NOT NULL DEFAULT '0', "level" integer NOT NULL DEFAULT '1', "status" character varying NOT NULL DEFAULT 'active', "last_login" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "title" character varying NOT NULL, "body" text, "data_json" jsonb, "is_read" boolean NOT NULL DEFAULT false, "channel" character varying, "sent_at" TIMESTAMP NOT NULL DEFAULT now(), "read_at" TIMESTAMP, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "features" ("id" character varying(50) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "module_id" character varying(50) NOT NULL, CONSTRAINT "PK_5c1e336df2f4a7051e5bf08a941" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "modules" ("id" character varying(50) NOT NULL, "name" character varying(255) NOT NULL, "description" text, CONSTRAINT "PK_7dbefd488bd96c5bf31f0ce0c95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mobile_units" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" character varying NOT NULL, "description" text, "driver_name" character varying, "contact_number" character varying, "current_location" geography(Point,4326), "status" character varying NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_07fbc5bc00f69c787bcef253ba0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7abcbdd83b8a1dcf7af11a95f7" ON "mobile_units" USING GiST ("current_location") `);
        await queryRunner.query(`CREATE TABLE "mobile_unit_routes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "mobile_unit_id" character varying NOT NULL, "destination_name" character varying NOT NULL, "location" geography(Point,4326) NOT NULL, "scheduled_at" TIMESTAMP NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', CONSTRAINT "PK_262e8ddc63e58703f39738564fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_de53f3de160faa644a54511ea3" ON "mobile_unit_routes" USING GiST ("location") `);
        await queryRunner.query(`CREATE TABLE "mentors" ("user_id" uuid NOT NULL, "bio" text, "specialties" jsonb, "experience_years" integer NOT NULL DEFAULT '0', "rating_avg" numeric(3,2) NOT NULL DEFAULT '0', "hourly_rate" numeric(15,2), "is_verified" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b81a5e23718af21c0d316a9a64c" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE TABLE "bookings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "mentor_id" uuid NOT NULL, "student_id" uuid NOT NULL, "slot_start" TIMESTAMP WITH TIME ZONE NOT NULL, "slot_end" TIMESTAMP WITH TIME ZONE NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "meeting_url" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "map_points" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "type_id" integer, "location" geography(Point,4326) NOT NULL, "address" character varying, "city" character varying, "photos" jsonb, "rating_avg" numeric(3,2) NOT NULL DEFAULT '0', "rating_count" integer NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'pending', "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_152d15807c9a61ccc24f3249388" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "educational_points" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "type" character varying NOT NULL, "location" geography(Point,4326) NOT NULL, "address" character varying, "is_verified" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_494eff0f22205287aeaf92c8229" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9e5971559042130695c8719f0c" ON "educational_points" USING GiST ("location") `);
        await queryRunner.query(`CREATE TABLE "learning_materials" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text, "type" character varying NOT NULL, "category" character varying NOT NULL, "tags" text array NOT NULL DEFAULT '{}', "file_url" character varying, "file_name" character varying, "mime_type" character varying, "view_count" integer NOT NULL DEFAULT '0', "download_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ae1ef944b64d9645383c5cc6da0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_learning_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "material_id" uuid NOT NULL, "progress" integer NOT NULL DEFAULT '0', "last_accessed" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_98f2b2215d0c973b5948338d907" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "learning_spots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "location" geography(Point,4326) NOT NULL, "type" character varying, "has_wifi" boolean NOT NULL DEFAULT true, "has_power_outlets" boolean NOT NULL DEFAULT true, "rating_avg" numeric(3,2) NOT NULL DEFAULT '0', "total_capacity" integer NOT NULL DEFAULT '50', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_90724075b19522c589d138f7c1f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a8112c6797754ff4b0eb028eca" ON "learning_spots" USING GiST ("location") `);
        await queryRunner.query(`CREATE TABLE "international_programs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "type" character varying NOT NULL, "description" text, "host_country" character varying, "organization" character varying, "application_deadline" TIMESTAMP WITH TIME ZONE, "benefits" jsonb, "apply_url" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1b61b3d2c12dfdec4381865eac6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "alumni_networks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "full_name" character varying NOT NULL, "university" character varying NOT NULL, "country" character varying NOT NULL, "major" character varying NOT NULL, "location" geography(Point,4326) NOT NULL, "contact_email" character varying, "status" character varying NOT NULL DEFAULT 'studying', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ae9647816a80901096c2348d146" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a2ed39ee3ca45d6139250e431b" ON "alumni_networks" USING GiST ("location") `);
        await queryRunner.query(`CREATE TABLE "internships" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "company_id" uuid NOT NULL, "title" character varying NOT NULL, "description" text NOT NULL, "field" character varying NOT NULL, "location_point" geography(Point,4326), "salary_range" character varying, "deadline" TIMESTAMP WITH TIME ZONE, "status" character varying NOT NULL DEFAULT 'open', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0a44e3c9dde1f2b92a4eb3c529f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5221ef7ef66c79fad1208cd1f8" ON "internships" USING GiST ("location_point") `);
        await queryRunner.query(`CREATE TABLE "university_counseling" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "university_name" character varying NOT NULL, "program_info" text, "contact_email" character varying, "admission_criteria" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5fe4f35d89b7cbd774454326bfb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hackathons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text, "start_date" TIMESTAMP WITH TIME ZONE NOT NULL, "end_date" TIMESTAMP WITH TIME ZONE NOT NULL, "status" character varying NOT NULL DEFAULT 'upcoming', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b290177bd925b16bf35bf59961b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hackathon_teams" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "team_name" character varying NOT NULL, "hackathon_id" uuid NOT NULL, "leader_id" uuid NOT NULL, "members" text array NOT NULL DEFAULT '{}', "repo_url" character varying, "demo_video" character varying, "status" character varying NOT NULL DEFAULT 'registered', "score" numeric(5,2), "feedback" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_698e891160d654b5763ff88c3a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "green_challenges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text, "points_reward" integer NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'active', "created_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_31276dff985b9fb9b3d9ca4eb72" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "green_challenge_activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "challenge_id" uuid NOT NULL, "carbon_saved_kg" numeric(10,2) NOT NULL DEFAULT '0', "points_earned" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_98b9f798a27ef75d994be2d83a5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "green_activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "activity_type" character varying NOT NULL, "description" text, "proof_url" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "ai_confidence" numeric(5,2) NOT NULL DEFAULT '0', "moderator_note" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_660d485f1bb5c4f83bc1f80ecf5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "badges" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" text, "category" character varying, "points_criteria" integer NOT NULL DEFAULT '0', "rarity" character varying NOT NULL DEFAULT 'common', CONSTRAINT "UQ_9c91fc9c4a4ae01712baad1e9f6" UNIQUE ("name"), CONSTRAINT "PK_8a651318b8de577e8e217676466" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_badges" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "badge_id" integer NOT NULL, "earned_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0ca139216824d745a930065706a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_points" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "points" integer NOT NULL, "action" character varying, "source_type" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b91f00258263b9d728c7b320674" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text, "type" character varying NOT NULL DEFAULT 'workshop', "location" character varying, "start_date" TIMESTAMP WITH TIME ZONE NOT NULL, "end_date" TIMESTAMP WITH TIME ZONE NOT NULL, "capacity" integer NOT NULL DEFAULT '100', "registered_count" integer NOT NULL DEFAULT '0', "banner_url" character varying, "organizer_id" character varying, "status" character varying NOT NULL DEFAULT 'upcoming', "price" numeric(10,2) NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_40731c7151fe4be3116e45ddf73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "event_registrations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "event_id" character varying NOT NULL, "user_id" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'registered', "ticket_code" character varying NOT NULL, "checked_in_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5815fd904b21dca8f8f0eb4f60b" UNIQUE ("ticket_code"), CONSTRAINT "PK_953d3b862c2487289a92b2356e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "donation_campaigns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text, "target_amount" numeric(15,2) NOT NULL DEFAULT '0', "current_amount" numeric(15,2) NOT NULL DEFAULT '0', "end_date" TIMESTAMP WITH TIME ZONE, "status" character varying NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d592dfa0964d30ef0095c66b45a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "donations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "campaign_id" uuid NOT NULL, "donor_id" uuid, "amount" numeric(15,2) NOT NULL, "status" character varying NOT NULL DEFAULT 'completed', "transaction_id" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c01355d6f6f50fc6d1b4a946abf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "privacy" character varying NOT NULL DEFAULT 'public', "owner_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_659d1483316afb28afd3a90646e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "posts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "author_id" uuid NOT NULL, "group_id" uuid, "title" character varying NOT NULL, "content" text NOT NULL, "like_count" integer NOT NULL DEFAULT '0', "comment_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "post_id" uuid NOT NULL, "author_id" uuid NOT NULL, "content" text NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8bf68bc960f2b69e818bdb90dcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "chat_messages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sender_id" uuid NOT NULL, "receiver_id" uuid, "content" text NOT NULL, "is_read" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_40c55ee0e571e268b0d3cd37d10" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "certificates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" character varying NOT NULL, "title" character varying NOT NULL, "issued_at" TIMESTAMP WITH TIME ZONE NOT NULL, "issuer" character varying NOT NULL, "verify_code" character varying NOT NULL, "qr_url" character varying, "pdf_url" character varying, "blockchain_metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_86cd517e24d6441d5ab2d4ec2a0" UNIQUE ("verify_code"), CONSTRAINT "PK_e4c7e31e2144300bea7d89eb165" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_86cd517e24d6441d5ab2d4ec2a" ON "certificates" ("verify_code") `);
        await queryRunner.query(`CREATE TABLE "career_paths" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "field" character varying, "description" text, "skills_required" jsonb, "roadmap_json" jsonb, "salary_range" character varying, "demand_level" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2051ef7b447c3939c5177a10f3c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "support_tickets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subject" character varying NOT NULL, "description" text NOT NULL, "status" character varying NOT NULL DEFAULT 'open', "priority" character varying NOT NULL DEFAULT 'normal', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, "assignedToId" uuid, CONSTRAINT "PK_942e8d8f5df86100471d2324643" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "business_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "name" character varying NOT NULL, "description" text, "industry" character varying, "website" character varying, "logo_url" character varying, "is_verified" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8be7137c2fb272571e2c6ad02ea" UNIQUE ("name"), CONSTRAINT "REL_1ceee77c549695cfc7c246224e" UNIQUE ("user_id"), CONSTRAINT "PK_29525485b1db8e87caf6a5ef042" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" character varying NOT NULL, "resource" character varying NOT NULL, "resource_id" character varying, "old_data" jsonb, "new_data" jsonb, "ip_address" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "userId" uuid, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "education_stats" ("id" SERIAL NOT NULL, "region" character varying NOT NULL, "province" character varying NOT NULL, "metric_type" character varying NOT NULL, "value" double precision NOT NULL, "year" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e7dabb27d9782680847e3a09152" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "wifi_locations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "location_point" geography(Point,4326), "address" character varying, "speed_mbps" double precision, "is_free" boolean NOT NULL DEFAULT true, "password" character varying, "password_hint" character varying, "verified" boolean NOT NULL DEFAULT false, "reported_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_afe21756f31c5076b8b209bcdd5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9620d9bb687ed0d69c687524fe" ON "wifi_locations" USING GiST ("location_point") `);
        await queryRunner.query(`CREATE TABLE "volunteer_activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text, "campaign_name" character varying, "hours" integer NOT NULL DEFAULT '0', "date" date NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "volunteer_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3efd8edddd34a24495e6dfb1651" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "surveys" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "questions_json" jsonb NOT NULL, "created_by_id" uuid NOT NULL, "status" character varying NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1b5e3d4aaeb2321ffa98498c971" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "survey_responses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "survey_id" uuid NOT NULL, "user_id" uuid NOT NULL, "answers_json" jsonb NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_349995c51959d139d8e485a58ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "summer_campaigns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "year" integer NOT NULL, "location" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'active', "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c2e530998331ded60d74e8f660f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stem_labs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" text, "location_point" geography(Point,4326), "equipment" text array NOT NULL DEFAULT '{}', "capacity" integer NOT NULL DEFAULT '0', "booking_available" boolean NOT NULL DEFAULT true, "contact" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9408a1ada96b9f6638c7f0a77a9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9657186a441f8c47ae438c9e5d" ON "stem_labs" USING GiST ("location_point") `);
        await queryRunner.query(`CREATE TABLE "shared_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "category" character varying, "description" text, "status" character varying NOT NULL DEFAULT 'available', "owner_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2c686236d4de082a837b2cd8f73" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "borrow_requests" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "item_id" uuid NOT NULL, "requester_id" uuid NOT NULL, "message" text, "status" character varying NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dd534a057b1e97d763fb193973f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "scholarships" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying NOT NULL, "description" text, "provider" character varying, "location" geography(Point,4326), "value_amount" numeric(15,2), "deadline" TIMESTAMP, "eligibility_criteria" jsonb, "apply_url" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_2a0dde777a7801b91882e4e69e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "scholarship_applications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "scholarship_id" uuid NOT NULL, "student_id" uuid NOT NULL, "personal_statement" text, "cv_url" character varying, "status" character varying NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1c42144a670e59aead3ca5e25e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "data_json"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "channel"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "sent_at"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "read_at"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "description" text`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "data_json" jsonb`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "channel" character varying`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "sent_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "read_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "type" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "data" jsonb`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "PK_c1433d71a4838793a49dcad46ab"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "body" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "features" ADD CONSTRAINT "FK_f794c9f7a049eff343e58c63222" FOREIGN KEY ("module_id") REFERENCES "modules"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mentors" ADD CONSTRAINT "FK_b81a5e23718af21c0d316a9a64c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_5b43b6aad3aeabd7b009746eb1a" FOREIGN KEY ("mentor_id") REFERENCES "mentors"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_802239bcb6f913e1b959ee587ba" FOREIGN KEY ("student_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "map_points" ADD CONSTRAINT "FK_0ea902b7fc45ec024fb31582b68" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_learning_history" ADD CONSTRAINT "FK_67a254e1c83473ec59b61895b52" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_learning_history" ADD CONSTRAINT "FK_021a68dad48f30515fc72d26c33" FOREIGN KEY ("material_id") REFERENCES "learning_materials"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "internships" ADD CONSTRAINT "FK_f65b0e67897cc068d7151c03b20" FOREIGN KEY ("company_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hackathon_teams" ADD CONSTRAINT "FK_4fff1b846ccc278549316ecc989" FOREIGN KEY ("hackathon_id") REFERENCES "hackathons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hackathon_teams" ADD CONSTRAINT "FK_f7128a1786182318c385a01ce7d" FOREIGN KEY ("leader_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "green_challenges" ADD CONSTRAINT "FK_4b35a133f9ad2367885e09c2481" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "green_challenge_activities" ADD CONSTRAINT "FK_0b0cd8fd4f71ceddd0417cf7bae" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "green_challenge_activities" ADD CONSTRAINT "FK_9e93220d8d3adc557665368ff84" FOREIGN KEY ("challenge_id") REFERENCES "green_challenges"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "green_activities" ADD CONSTRAINT "FK_be70e6db283e7b1afdfb6a8a5fd" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_badges" ADD CONSTRAINT "FK_f1221d9b1aaa64b1f3c98ed46d3" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_badges" ADD CONSTRAINT "FK_715b81e610ab276ff6603cfc8e8" FOREIGN KEY ("badge_id") REFERENCES "badges"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_points" ADD CONSTRAINT "FK_b63a87a96091c755b78a75eecbc" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "donations" ADD CONSTRAINT "FK_6ad4405f42816956aa8a89bc9fb" FOREIGN KEY ("campaign_id") REFERENCES "donation_campaigns"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "donations" ADD CONSTRAINT "FK_6d627a82b263d4ad02bd2255930" FOREIGN KEY ("donor_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_5d7af25843377def343ab0beaa8" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_312c63be865c81b922e39c2475e" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "posts" ADD CONSTRAINT "FK_7628aa3741a30d6217271a226cf" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_259bf9825d9d198608d1b46b0b5" FOREIGN KEY ("post_id") REFERENCES "posts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comments" ADD CONSTRAINT "FK_e6d38899c31997c45d128a8973b" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_9e5fc47ecb06d4d7b84633b1718" FOREIGN KEY ("sender_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chat_messages" ADD CONSTRAINT "FK_c1787d1874556cb9eb0483a7e2b" FOREIGN KEY ("receiver_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "certificates" ADD CONSTRAINT "FK_88f90b1b9c635c14271e509cec0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support_tickets" ADD CONSTRAINT "FK_8679e2ff150ff0e253189ca0253" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "support_tickets" ADD CONSTRAINT "FK_947e77544ab7d5fd9521c44e069" FOREIGN KEY ("assignedToId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_profiles" ADD CONSTRAINT "FK_1ceee77c549695cfc7c246224ef" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_692a909ee0fa9383e7859f9b406" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_cfa83f61e4d27a87fcae1e025ab" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wifi_locations" ADD CONSTRAINT "FK_350b5eea6ad11f1d3923b9947c8" FOREIGN KEY ("reported_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "volunteer_activities" ADD CONSTRAINT "FK_24973cf272ed463bf64a6f4a019" FOREIGN KEY ("volunteer_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "surveys" ADD CONSTRAINT "FK_ed63005b2c83de54855639c4f38" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "survey_responses" ADD CONSTRAINT "FK_2b4e3f83ce0b4a0d7617ac0cd44" FOREIGN KEY ("survey_id") REFERENCES "surveys"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "survey_responses" ADD CONSTRAINT "FK_15c9124bfeb633545c5de42edb6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shared_items" ADD CONSTRAINT "FK_ae35f880148bc3a97724af63f7b" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "borrow_requests" ADD CONSTRAINT "FK_1a8ac13e7be83c37419654f250a" FOREIGN KEY ("item_id") REFERENCES "shared_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "borrow_requests" ADD CONSTRAINT "FK_ae71e4e8e347da0360916e67ab2" FOREIGN KEY ("requester_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scholarship_applications" ADD CONSTRAINT "FK_2c9e0c62af26956ca61f8616a7f" FOREIGN KEY ("scholarship_id") REFERENCES "scholarships"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "scholarship_applications" ADD CONSTRAINT "FK_41ab6c7fb59a9fd5ba8a15885cd" FOREIGN KEY ("student_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "scholarship_applications" DROP CONSTRAINT "FK_41ab6c7fb59a9fd5ba8a15885cd"`);
        await queryRunner.query(`ALTER TABLE "scholarship_applications" DROP CONSTRAINT "FK_2c9e0c62af26956ca61f8616a7f"`);
        await queryRunner.query(`ALTER TABLE "borrow_requests" DROP CONSTRAINT "FK_ae71e4e8e347da0360916e67ab2"`);
        await queryRunner.query(`ALTER TABLE "borrow_requests" DROP CONSTRAINT "FK_1a8ac13e7be83c37419654f250a"`);
        await queryRunner.query(`ALTER TABLE "shared_items" DROP CONSTRAINT "FK_ae35f880148bc3a97724af63f7b"`);
        await queryRunner.query(`ALTER TABLE "survey_responses" DROP CONSTRAINT "FK_15c9124bfeb633545c5de42edb6"`);
        await queryRunner.query(`ALTER TABLE "survey_responses" DROP CONSTRAINT "FK_2b4e3f83ce0b4a0d7617ac0cd44"`);
        await queryRunner.query(`ALTER TABLE "surveys" DROP CONSTRAINT "FK_ed63005b2c83de54855639c4f38"`);
        await queryRunner.query(`ALTER TABLE "volunteer_activities" DROP CONSTRAINT "FK_24973cf272ed463bf64a6f4a019"`);
        await queryRunner.query(`ALTER TABLE "wifi_locations" DROP CONSTRAINT "FK_350b5eea6ad11f1d3923b9947c8"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_cfa83f61e4d27a87fcae1e025ab"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_692a909ee0fa9383e7859f9b406"`);
        await queryRunner.query(`ALTER TABLE "business_profiles" DROP CONSTRAINT "FK_1ceee77c549695cfc7c246224ef"`);
        await queryRunner.query(`ALTER TABLE "support_tickets" DROP CONSTRAINT "FK_947e77544ab7d5fd9521c44e069"`);
        await queryRunner.query(`ALTER TABLE "support_tickets" DROP CONSTRAINT "FK_8679e2ff150ff0e253189ca0253"`);
        await queryRunner.query(`ALTER TABLE "certificates" DROP CONSTRAINT "FK_88f90b1b9c635c14271e509cec0"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_c1787d1874556cb9eb0483a7e2b"`);
        await queryRunner.query(`ALTER TABLE "chat_messages" DROP CONSTRAINT "FK_9e5fc47ecb06d4d7b84633b1718"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_e6d38899c31997c45d128a8973b"`);
        await queryRunner.query(`ALTER TABLE "comments" DROP CONSTRAINT "FK_259bf9825d9d198608d1b46b0b5"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_7628aa3741a30d6217271a226cf"`);
        await queryRunner.query(`ALTER TABLE "posts" DROP CONSTRAINT "FK_312c63be865c81b922e39c2475e"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_5d7af25843377def343ab0beaa8"`);
        await queryRunner.query(`ALTER TABLE "donations" DROP CONSTRAINT "FK_6d627a82b263d4ad02bd2255930"`);
        await queryRunner.query(`ALTER TABLE "donations" DROP CONSTRAINT "FK_6ad4405f42816956aa8a89bc9fb"`);
        await queryRunner.query(`ALTER TABLE "user_points" DROP CONSTRAINT "FK_b63a87a96091c755b78a75eecbc"`);
        await queryRunner.query(`ALTER TABLE "user_badges" DROP CONSTRAINT "FK_715b81e610ab276ff6603cfc8e8"`);
        await queryRunner.query(`ALTER TABLE "user_badges" DROP CONSTRAINT "FK_f1221d9b1aaa64b1f3c98ed46d3"`);
        await queryRunner.query(`ALTER TABLE "green_activities" DROP CONSTRAINT "FK_be70e6db283e7b1afdfb6a8a5fd"`);
        await queryRunner.query(`ALTER TABLE "green_challenge_activities" DROP CONSTRAINT "FK_9e93220d8d3adc557665368ff84"`);
        await queryRunner.query(`ALTER TABLE "green_challenge_activities" DROP CONSTRAINT "FK_0b0cd8fd4f71ceddd0417cf7bae"`);
        await queryRunner.query(`ALTER TABLE "green_challenges" DROP CONSTRAINT "FK_4b35a133f9ad2367885e09c2481"`);
        await queryRunner.query(`ALTER TABLE "hackathon_teams" DROP CONSTRAINT "FK_f7128a1786182318c385a01ce7d"`);
        await queryRunner.query(`ALTER TABLE "hackathon_teams" DROP CONSTRAINT "FK_4fff1b846ccc278549316ecc989"`);
        await queryRunner.query(`ALTER TABLE "internships" DROP CONSTRAINT "FK_f65b0e67897cc068d7151c03b20"`);
        await queryRunner.query(`ALTER TABLE "user_learning_history" DROP CONSTRAINT "FK_021a68dad48f30515fc72d26c33"`);
        await queryRunner.query(`ALTER TABLE "user_learning_history" DROP CONSTRAINT "FK_67a254e1c83473ec59b61895b52"`);
        await queryRunner.query(`ALTER TABLE "map_points" DROP CONSTRAINT "FK_0ea902b7fc45ec024fb31582b68"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_802239bcb6f913e1b959ee587ba"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_5b43b6aad3aeabd7b009746eb1a"`);
        await queryRunner.query(`ALTER TABLE "mentors" DROP CONSTRAINT "FK_b81a5e23718af21c0d316a9a64c"`);
        await queryRunner.query(`ALTER TABLE "features" DROP CONSTRAINT "FK_f794c9f7a049eff343e58c63222"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "notifications" ALTER COLUMN "body" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "PK_c1433d71a4838793a49dcad46ab"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "id" character varying(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "data"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "read_at"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "sent_at"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "channel"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "data_json"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP COLUMN "description"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "read_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "sent_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "channel" character varying`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "data_json" jsonb`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ADD "description" text`);
        await queryRunner.query(`DROP TABLE "scholarship_applications"`);
        await queryRunner.query(`DROP TABLE "scholarships"`);
        await queryRunner.query(`DROP TABLE "borrow_requests"`);
        await queryRunner.query(`DROP TABLE "shared_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9657186a441f8c47ae438c9e5d"`);
        await queryRunner.query(`DROP TABLE "stem_labs"`);
        await queryRunner.query(`DROP TABLE "summer_campaigns"`);
        await queryRunner.query(`DROP TABLE "survey_responses"`);
        await queryRunner.query(`DROP TABLE "surveys"`);
        await queryRunner.query(`DROP TABLE "volunteer_activities"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9620d9bb687ed0d69c687524fe"`);
        await queryRunner.query(`DROP TABLE "wifi_locations"`);
        await queryRunner.query(`DROP TABLE "education_stats"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "business_profiles"`);
        await queryRunner.query(`DROP TABLE "support_tickets"`);
        await queryRunner.query(`DROP TABLE "career_paths"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_86cd517e24d6441d5ab2d4ec2a"`);
        await queryRunner.query(`DROP TABLE "certificates"`);
        await queryRunner.query(`DROP TABLE "chat_messages"`);
        await queryRunner.query(`DROP TABLE "comments"`);
        await queryRunner.query(`DROP TABLE "posts"`);
        await queryRunner.query(`DROP TABLE "groups"`);
        await queryRunner.query(`DROP TABLE "donations"`);
        await queryRunner.query(`DROP TABLE "donation_campaigns"`);
        await queryRunner.query(`DROP TABLE "event_registrations"`);
        await queryRunner.query(`DROP TABLE "events"`);
        await queryRunner.query(`DROP TABLE "user_points"`);
        await queryRunner.query(`DROP TABLE "user_badges"`);
        await queryRunner.query(`DROP TABLE "badges"`);
        await queryRunner.query(`DROP TABLE "green_activities"`);
        await queryRunner.query(`DROP TABLE "green_challenge_activities"`);
        await queryRunner.query(`DROP TABLE "green_challenges"`);
        await queryRunner.query(`DROP TABLE "hackathon_teams"`);
        await queryRunner.query(`DROP TABLE "hackathons"`);
        await queryRunner.query(`DROP TABLE "university_counseling"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5221ef7ef66c79fad1208cd1f8"`);
        await queryRunner.query(`DROP TABLE "internships"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2ed39ee3ca45d6139250e431b"`);
        await queryRunner.query(`DROP TABLE "alumni_networks"`);
        await queryRunner.query(`DROP TABLE "international_programs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8112c6797754ff4b0eb028eca"`);
        await queryRunner.query(`DROP TABLE "learning_spots"`);
        await queryRunner.query(`DROP TABLE "user_learning_history"`);
        await queryRunner.query(`DROP TABLE "learning_materials"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9e5971559042130695c8719f0c"`);
        await queryRunner.query(`DROP TABLE "educational_points"`);
        await queryRunner.query(`DROP TABLE "map_points"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP TABLE "mentors"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de53f3de160faa644a54511ea3"`);
        await queryRunner.query(`DROP TABLE "mobile_unit_routes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7abcbdd83b8a1dcf7af11a95f7"`);
        await queryRunner.query(`DROP TABLE "mobile_units"`);
        await queryRunner.query(`DROP TABLE "modules"`);
        await queryRunner.query(`DROP TABLE "features"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3e22934a7a2b943002a81c48f"`);
        await queryRunner.query(`DROP TABLE "opportunities"`);
        await queryRunner.query(`DROP TABLE "roles"`);
    }

}
