name: Sync to Hugging Face space
on:
  push:
    branches: [main]
  # Cho phép chạy thủ công từ tab Actions
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          
          
          # Đẩy code lên Hugging Face (Thay username và tên Space của bạn vào đường dẫn dưới)
          # Ví dụ: https://tancse2005:${HF_TOKEN}@huggingface.co/spaces/tancse2005/Edumap
          git push --force https://tancse2005:${HF_TOKEN}@huggingface.co/spaces/tancse2005/Edumap HEAD:main
